### ISSUE TITLE
suggest changing font a little

### ISSUE THREAD

**Issue by HongPong** [lmcinnes/datamapplot_examples#1]
Hi, this thing is very cool. 

My only suggestion is to change the font a bit. It seems like the shading - maybe box shading? thins out the letters too much. Blockier letters, heavier font weight, or a different kind of shading (eg background colors for inline elements) could make the smaller texts more legible. Best regards!

**Comment by lmcinnes** [comment]
Thanks. This was all generated via the [interactive plot features of DataMapPlot](https://datamapplot.readthedocs.io/en/latest/interactive_intro.html). It doesn't take much code to make the plot -- see https://datamapplot.readthedocs.io/en/latest/auto_examples/plot_interactive_arxiv_ml.html#sphx-glr-auto-examples-plot-interactive-arxiv-ml-py 

It supports any font on google fonts, so you can always substitute your preferred font and generate your own version.

**Comment by HongPong** [comment]
cool cheers - very cyberpunk it was fun to check out.
