### ISSUE TITLE
Question: reproduction instructions/scripts

### ISSUE THREAD

**Issue by karelin** [lmcinnes/datamapplot_examples#2]
Thank you Leland for very nice demos.
Are there any scripts/notebooks/instructions on reproducing (data preparation)?
Thanks!

**Comment by lmcinnes** [comment]
I don't have the data prep notebooks anywhere as a lot of it was ad hoc at the time it was done -- it was essentially learning how to build the tools to do it as I went. The current tooling is getting more solid, so I do hope to be able to release some notebooks for the more recent examples soon.

**Comment by karelin** [comment]
Thank you very much for reply.
Looking forward to have more examples and details ;)
